# Generated by Django 5.0.3 on 2024-03-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacType', models.CharField(max_length=255)),
                ('isTenureBased', models.BooleanField()),
                ('employmentStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GradeMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isCreditCounted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('txstProfile', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('facultyType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.facultytype')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField()),
                ('hasLab', models.BooleanField()),
                ('isLabRequired', models.BooleanField()),
                ('courseCredits', models.IntegerField()),
                ('labCredits', models.IntegerField()),
                ('courseAttributes', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('gradeMode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.grademode')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('building', models.CharField(max_length=255)),
                ('reqAccessCard', models.BooleanField()),
                ('maxOccupancy', models.IntegerField()),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.roomtype')),
            ],
        ),
    ]
