# Generated by Django 5.0.3 on 2024-03-28 05:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courseprerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprerequisite',
            name='Condition',
            field=models.CharField(default=datetime.datetime(2024, 3, 28, 5, 35, 3, 582748, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='Type',
            field=models.CharField(default='Mandetory', max_length=255),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_prerequisites', to='main.course'),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_prerequisite_for', to='main.course'),
        ),
        migrations.CreateModel(
            name='CourseCorequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='Mandetory', max_length=255)),
                ('Condition', models.CharField(default="grade of 'C' or better", max_length=255)),
                ('corequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_corequisite_for', to='main.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_corequisites', to='main.course')),
            ],
            options={
                'unique_together': {('course', 'corequisite')},
            },
        ),
    ]
