# Generated by Django 5.0.3 on 2024-03-29 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courseprerequisite_condition_courseprerequisite_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultytype',
            name='FacType',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract')], max_length=255),
        ),
    ]
