# Generated by Django 5.0.3 on 2024-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department_code_alter_facultytype_factype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecorequisite',
            name='Type',
            field=models.CharField(choices=[('Mandetory', 'Mandetory'), ('Choice', 'Choice')], default='Mandetory', max_length=255),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='Condition',
            field=models.CharField(default="grade of 'C' or better", max_length=255),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='Type',
            field=models.CharField(choices=[('Mandetory', 'Mandetory'), ('Choice', 'Choice')], default='Mandetory', max_length=255),
        ),
    ]
