# Generated by Django 5.0.3 on 2024-04-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprerequisite',
            name='Type',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Choice', 'Choice')], default='Mandetory', max_length=255),
        ),
    ]
