# Generated by Django 5.0.3 on 2024-03-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_courseprerequisite_condition_courseprerequisite_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('semester', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Trashed', 'Trashed')], default='Draft', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_labs', models.IntegerField(default=0)),
                ('number_of_sections', models.IntegerField(default=1)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_courses', to='schedulebuilder.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.faculty')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schdule_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulecourse')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionType', models.CharField(choices=[('Class', 'Class'), ('Lab', 'Lab')], default='Class', max_length=255)),
                ('section_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulefaculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.scheduleroom')),
                ('schedule_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schedulebuilder.schedulecourse')),
            ],
            options={
                'unique_together': {('schedule_course', 'section_name', 'room', 'start_time', 'end_time')},
            },
        ),
    ]
