# Generated by Django 5.0.3 on 2024-03-29 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department_code_alter_facultytype_factype'),
        ('schedulebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room'),
        ),
    ]
