# Generated by Django 5.0.3 on 2024-04-08 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_coursecorequisite_type_and_more'),
        ('schedulebuilder', '0002_scheduleroom_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesection',
            unique_together={('schedule_course', 'section_name', 'sectionType', 'room', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='code',
            field=models.CharField(default='EE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='course_credit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='lab_credit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulecourse',
            name='name',
            field=models.CharField(default='A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulefaculty',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulefaculty',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduleroom',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleroom',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulesection',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulesection',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedulecourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulecourse',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedule'),
        ),
    ]
