# Generated by Django 5.0.3 on 2024-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0003_alter_schedulesection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
