# Generated by Django 5.0.3 on 2024-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0004_alter_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default='EE', unique=True),
            preserve_default=False,
        ),
    ]
