# Generated by Django 5.0.3 on 2024-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0005_schedule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
