# Generated by Django 5.0.3 on 2024-04-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_coursecorequisite_type_and_more'),
        ('schedulebuilder', '0006_alter_schedule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course'),
        ),
    ]
