# Generated by Django 5.0.3 on 2024-04-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0007_alter_schedulecourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesection',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedule'),
            preserve_default=False,
        ),
    ]
