# Generated by Django 5.0.3 on 2024-04-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_coursecorequisite_type_and_more'),
        ('schedulebuilder', '0008_schedulesection_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department'),
        ),
    ]
