# Generated by Django 5.0.3 on 2024-04-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_semester'),
        ('schedulebuilder', '0009_schedule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.semester'),
        ),
    ]
