# Generated by Django 5.0.3 on 2024-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0010_alter_schedule_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesection',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulesection',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
