# Generated by Django 5.0.3 on 2024-04-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0011_alter_schedulesection_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesection',
            name='schedule_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulecourse'),
        ),
    ]
