# Generated by Django 5.0.3 on 2024-04-12 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0012_alter_schedulesection_schedule_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesection',
            unique_together={('schedule_course', 'section_name', 'sectionType', 'room')},
        ),
        migrations.RemoveField(
            model_name='schedulesection',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedulesection',
            name='start_time',
        ),
        migrations.CreateModel(
            name='ScheduleSectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thrusday'), ('F', 'Friday')], max_length=255, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedule')),
                ('schedule_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulecourse')),
                ('schedule_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulesection')),
            ],
            options={
                'unique_together': {('schedule', 'schedule_course', 'schedule_section', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
