# Generated by Django 5.0.3 on 2024-04-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0013_alter_schedulesection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesection',
            unique_together={('schedule_course', 'section_name', 'sectionType')},
        ),
        migrations.RemoveField(
            model_name='schedulesection',
            name='room',
        ),
    ]
