# Generated by Django 5.0.3 on 2024-04-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0014_alter_schedulesection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulesectiontime',
            options={'verbose_name_plural': 'Schedule Section Times'},
        ),
        migrations.AlterUniqueTogether(
            name='schedulesectiontime',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='schedulesection',
            name='faculty',
        ),
        migrations.AddField(
            model_name='schedulesectiontime',
            name='schedule_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulefaculty'),
        ),
        migrations.AlterField(
            model_name='schedulesectiontime',
            name='day',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedulesectiontime',
            unique_together={('schedule', 'schedule_course', 'schedule_faculty', 'schedule_section', 'day', 'start_time', 'end_time')},
        ),
    ]
