# Generated by Django 5.0.3 on 2024-04-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0015_alter_schedulesectiontime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulesectiontime',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='schedulesectiontime',
            unique_together={('schedule', 'schedule_course', 'schedule_section', 'day', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='schedulesection',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulebuilder.schedulefaculty'),
        ),
        migrations.AlterField(
            model_name='schedulesectiontime',
            name='day',
            field=models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thrusday'), ('F', 'Friday')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='schedulesectiontime',
            name='schedule_faculty',
        ),
    ]
