# Generated by Django 5.0.3 on 2024-04-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0016_alter_schedulesectiontime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesectiontime',
            name='day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
