# Generated by Django 5.0.3 on 2024-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0017_alter_schedulesectiontime_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedulesection',
            name='day',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='schedulesection',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulesection',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedulesection',
            unique_together={('schedule_course', 'section_name', 'sectionType', 'day', 'start_time', 'end_time')},
        ),
        migrations.DeleteModel(
            name='ScheduleSectionTime',
        ),
    ]
