# Generated by Django 5.0.3 on 2024-04-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulebuilder', '0018_alter_schedulesection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesection',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedulebuilder.schedulefaculty'),
        ),
    ]
